project:
  type: website
  output-dir: docs
  
website:
  title: "Li Ying"
  favicon: img/logo.png
  
  # navigation bar at the top of the web
  navbar:
    logo: img/logo.png
    background: primary
    search: true
    
    # sub-pages
    left:
      - text: "About"
        href: about.qmd
      - text: "Education"
        href: education.qmd
      - text: "Experience/Projects"
        href: projects.qmd
      - text: "Resume"
        href: resume.qmd
        
  #footer
  page-footer:
    left: Copyright 2025, Soh Li Ying
    right: This website is built with {{< fa heart >}} and [Quarto](https://quarto.org/)
        
preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    theme: 
      - theme.scss
    fontsize: 1.35em
    toc: true
    fig-cap-location: margin
    anchor-sections: true
    reference-location: margin
    grid:
      sidebar-width: 100px
      body-width: 950px
      margin-width: 200px
      gutter-width: 1.5rem

editor: visual

