project:
  type: website
  output-dir: docs
  
website:
  title: "Li Ying"
  favicon: img/logo.png
  
  # navigation bar at the top of the web
  navbar:
    logo: img/frog_book.png
    background: primary
    search: true
    
    # sub-pages
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Education"
        file: education.qmd
      - text: "Experiences"
        file: experiences.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "CV"
        file: CV.qmd
      
        
preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.35em
    theme: lux
    css: styles.css
    toc: true
    fig-cap-location: margin
    anchor-sections: true
    reference-location: margin

editor: visual

