---
title: "About"
subtitle: "A little bit more about me"
---

## {{< fa coffee >}} Me.

I am currently a final year undergraduate at the [National University of Singapore](https://nus.edu.sg/), pursuing a [Bachelor's in Business Administration](https://bba.nus.edu.sg/) with a major in Marketing alongside a minor in [Interactive Media Development](https://fass.nus.edu.sg/cnm/undergraduate-minor-imd/). As I was introduced to the world of coding a tad later than my peers, I was really apprehensive towards this field. But thankfully I was surrounded by some really supportive professors/instructors and peers who gave me immense help to make up for being a 'laggard'.

With that being said, I am also a good team player who's not afraid to experiment with fresh things. I really believe in the importance of being an eager self-directed learner, hence and I enjoy gaining new knowledge along the way.

## {{< fa smile >}} Hobbies.

I feel very fortunate to have the ability to indulge in many of the things that i love *a lot* now. Albeit university life can be taxing (with all the never-ending assignments, quizzes, and project...), I allow myself to unwind and relax through things that I take interest in.

I enjoy gaming, journaling, and doodling. The logo I am currently using is designed myself when I first started experimenting with Procreate.

