---
title: "Education"
---

## NATIONAL UNIVERSITY OF SINGAPORE (NUS)
*Major in Bachelor of Business Administration with Minor in Interactive Media Development*  
•	Current CAP Score: 4.38/5.0

#### {{< fa certificate >}} Skills. 

I possess a proactive approach towards skill acquisition, driven by a desire to excel both academically and professionally. This inclination has led me to undertake a series of online courses, motivated by both curiosity and a pragmatic concern for remaining competitive. In fact, this website was built from scratch with the help of online tutorials about Quarto! Below are some of the skills I have cultivated through these endeavors:   

<div>
  <i class="fa-solid fa-brands fa-python fa-5x" style="margin-right: 40px;"></i>
  <i class="fa-solid fa-brands fa-figma fa-5x" style="margin-right: 40px;"></i>
  <i class="fa-solid fa-brands fa-r-project fa-5x" style="margin-right: 40px;"></i>
  Google Analytics, and more!
</div>


#### {{< fa server >}} Achievements, Leadership & Committee Experiences.
**NUS ROTARACT CLUB**  
**Duration**: Aug 2021 - Aug 2022  
**Role**: Level In-Charge  
•	Facilitated welcome activities for over 100 active and new volunteers from different faculties in NUS  
•	Responsible for weekly lesson plans and worksheets alongside being in charge of overseeing and ensuring smooth execution of weekly tutoring sessions
 
**[NUS BUSINESS CAMP](https://liyinnng.github.io/school_projects/NBC/NBC.html)**	 
**Duration**: Sep 2021 - Jun 2022  
**Role**: Publicity Executive  
•	Led a faculty-wide publicity campaigns that attracted more than 600 sign-ups to be a participant of the 2022 NUS Business Camp  
•	Person in-charge of managing social-relations with students and public, accumulating over a thousand followers on Instagram
 
**NUS BIZCONNECT**  
**Duration**: Sep 2022 – Present  
**Role**: Publicity Executive  								    
•	Working with a team of 7 in bridging relations between undergraduates and alumni of NUS Business School to connect various like-minded individuals  
•	In-charge of social media marketing within the team to extend outreach of organized events to attract interested participants

---

## Nanyang Junior College 
*GCE ‘A’ Levels*  
•	**Achievement 4 distinctions** in Mathematics, General Paper, Physics and Economics  
•	**Involvement in Extracurricular Activities：**  
- International Service Learning Expedition Club  
- Dance Society

 



