---
  title: "data-story"
author: "Soh Li Ying"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=T,echo=TRUE}
library(tidyverse)
library(ggplot2)
library(dplyr)
social_media_health <- read.csv("social-media-and-mental-health.csv")
glimpse(social_media_health)
social_media_health

```


```{r, eval=T,echo=TRUE}
# Data filtering to find rs between age and usage of social media (line-graph, x-axis = age, y-axis = yes/no --> yes = 1, no = 0)

# Replacing 'Yes' with 1 and 'No' with 0
social_media_health <- social_media_health %>% 
  mutate(X6..Do.you.use.social.media. = ifelse(trimws(X6..Do.you.use.social.media.) == "Yes", 1, 0))

social_media_health

```

```{r, eval=T,echo=TRUE}
# Data filtering to find rs between gender, frequency of seeking validation from SM and frequency of feeling depressed or down 

gender_validation_depressed <- select(social_media_health, X2..Gender, X17..How.often.do.you.look.to.seek.validation.from.features.of.social.media., X18..How.often.do.you.feel.depressed.or.down.)

gender_validation_depressed

```
```{r, eval=T,echo=TRUE}
# Data filtering to find rs between age, frequency of seeking validation from SM and frequency of feeling depressed or down 

age_frequency_depressed <- select(social_media_health, X1..What.is.your.age., X17..How.often.do.you.look.to.seek.validation.from.features.of.social.media., X18..How.often.do.you.feel.depressed.or.down.)

age_frequency_depressed

```


```{r, eval=T,echo=TRUE}

# new social media addiction dataset 
social_media_addiction <- read.csv("social-media-addiction.csv")
glimpse(social_media_addiction)

```

```{r, eval=T,echo=TRUE}
hate_comments <- read.csv("hate.csv")
glimpse(hate_comments)



```